backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  branch: master

media_folder: src/images
public_folder: src/images

display_url: https://stclementofohrid.ca/

collections:
  - label: "Religious Blog in English"
    name: "religious_blog_en"
    folder: "_posts/religious_blog"
    filter: {field: "language", value: "en"}
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "mkd"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Photo Gallery", name: "galleryImages", widget: "list", field: {label: "Image", name: "image", widget: "image"}}
  - label: "Верски Блог на Македонски"
    name: "religious_blog_mkd"
    folder: "_posts/religious_blog"
    filter: {field: "language", value: "mkd"}
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - {label: "Јазик", name: "language", widget: "select", options: ["en", "mkd"]}
      - {label: "Наслов", name: "title", widget: "string"}
      - {label: "Датум на Објавување", name: "date", widget: "datetime"}
      - {label: "Слика", name: "thumbnail", widget: "image"}
      - {label: "Тело", name: "body", widget: "markdown"}
      - {label: "Фото Галерија", name: "galleryImages", widget: "list", field: {label: "Фото", name: "image", widget: "image"}}